languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
baseurl = "/"
googleAnalytics = ""
theme = "hugo-vitae"

[params]
  author = "Sachin Jambhulkar"
  title = "Sachin Jambhulkar's Resume"
  description = "Sachin Jambhulkar's Awesome Resume"
  avatar = "person2.jpg"
  #email = "mail Dwai / "
  email_full = "mailto:sachin@cloudgear.io?subject=Got your resume"
  #website = "Resume pdf download"
  website_full = "http://jumbo.cloudgear.io/img/jumbo.pdf"
  github = "cloudgear-io"
  twitter = "cloudgeario"
  linkedin = "sachinjambhulkar"
  #tel = "+44 0000 000000"
  #tel_full = "+440000000000"
  google_maps = "https://www.google.com/maps/place/Bangalore"
  #address = "44 Perth Street"
  #postcode = "EH3 5BL"
  city = "Bangalore"
  country = "India"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
